[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

verbosity = 3

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
anvil = "http://localhost:8545"

[profile.heavy_fuzz.fuzz]
runs = 10000

[profile.superheavy_fuzz.fuzz]
runs = 100000
